#pragma once

#include <stm32g4xx_ll_exti.h>
#include <stm32g4xx_ll_gpio.h>
#include <stm32g4xx_ll_system.h>

#define DEBUG_TX_PIN LL_GPIO_PIN_2
#define DEBUG_TX_PORT GPIOA
#define DEBUG_RX_PIN LL_GPIO_PIN_3
#define DEBUG_PX_PORT GPIOA

#define GPS_TX_PIN LL_GPIO_PIN_9
#define GPS_TX_PORT GPIOA
#define GPS_RX_PIN LL_GPIO_PIN_10
#define GPS_RX_PORT GPIOA

#define GPS_RESET_PIN LL_GPIO_PIN_1
#define GPS_RESET_PORT GPIOA
#define GPS_PPS_PIN LL_GPIO_PIN_0
#define GPS_PPS_PORT GPIOA

#define DISPLAY_MOSI_PIN LL_GPIO_PIN_7
#define DISPLAY_MOSI_PORT GPIOA
#define DISPLAY_MISO_PIN LL_GPIO_PIN_6
#define DISPLAY_MISO_PORT GPIOA
#define DISPLAY_SCK_PIN LL_GPIO_PIN_5
#define DISPLAY_SCK_PORT GPIOA
#define DISPLAY_SS_PIN LL_GPIO_PIN_4
#define DISPLAY_SS_PORT GPIOA

#define DISPLAY_RESET_PIN LL_GPIO_PIN_0
#define DISPLAY_RESET_PORT GPIOB
#define DISPLAY_DC_PIN LL_GPIO_PIN_1
#define DISPLAY_DC_PORT GPIOB
#define DISPLAY_BUSY_PIN LL_GPIO_PIN_2
#define DISPLAY_BUSY_PORT GPIOB

#define DISPLAY_BUSY_IRQHandler EXTI2_IRQHandler
#define DISPLAY_BUSY_IRQn EXTI2_IRQn
#define DISPLAY_BUSY_EXTI_LINE LL_EXTI_LINE_2
#define DISPLAY_BUSY_SYSCFG_EXTI_PORT LL_SYSCFG_EXTI_PORTB
#define DISPLAY_BUSY_SYSCFG_EXTI_LINE LL_SYSCFG_EXTI_LINE2
